package com.sridharnagula.productservice.repositories;

import com.sridharnagula.productservice.models.Product;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductRepository extends JpaRepository<Product,Long> {
    Product save(Product p); // the attributes that are automatically generated by DB will not be
    // present in the Parameters, but will be there in return Object.
    // Mean Product p will not have id but the returned Product before save have id in it
}

//extends JpaRepository<Product,Long>
//Product - Entity with which ProductRepository is going to work
// Long - DataType of Primary key of the Product Entity

// Hibernate will implement the JpaRepository
