apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  serviceName: postgres-order
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orderService
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: db-credentials, key: ORDER_DB_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: db-credentials, key: ORDER_DB_PASSWORD }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  selector:
    app: postgres-order
  ports:
    - port: 5432
      targetPort: 5432
