spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5434}/userService
    username: ${USER_DB_USER:userServiceUser}
    password: ${USER_DB_PASSWORD:StrongPassword123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
